# Generated by Django 3.1.3 on 2020-11-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detectives',
            new_name='Detective',
        ),
    ]
